### ISSUE TITLE
Ability to specify inherited class from another class

### ISSUE THREAD

**Issue by Quenty** [UpliftGames/moonwave#102] opened 2021-12-28 02:21 UTC
It would be good to specify inherited properties on a class. Very important API members, like :Destroy() are inherited from certain classes and currently there's no way to specify this inherited model.

Even better would be automatic detection, however, I do not think this is easy or even possible with custom module loading systems right now.

https://robloxapi.github.io/ref/class/Frame.html

**Comment by evaera** [comment] 2021-12-28 02:23
Duplicate of #52?

**Closed** 2021-12-28 02:30 UTC
